Update auto_pr_title.yml

diff --git a/.github/workflows/auto_pr_title.yml b/.github/workflows/auto_pr_title.yml
--- a/.github/workflows/auto_pr_title.yml
+++ b/.github/workflows/auto_pr_title.yml
@@ -23,28 +23,33 @@ jobs:
         route: GET /repos/${{ github.repository }}/issues/${{ steps.extract.outputs.issue_number }}
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+- name: Update PR
+  run: |
+    ISSUE_TITLE=$(echo '${{ steps.issue.outputs.data }}' | jq -r .title)
+    if [ -z "$ISSUE_TITLE" ]; then
+      echo "Failed to fetch the issue title."
+      exit 1
+    fi
 
-    - name: Update PR
-      run: |
-        ISSUE_TITLE=$(echo '${{ steps.issue.outputs.data }}' | jq -r .title)
-        ASSIGNEES=$(echo '${{ steps.issue.outputs.data }}' | jq -r '.assignees[].login' | paste -sd ',' -)
-        LABELS=$(echo '${{ steps.issue.outputs.data }}' | jq -r '.labels[].name' | paste -sd ',' -)
+    ASSIGNEES=$(echo '${{ steps.issue.outputs.data }}' | jq -r '[.assignees[].login]' | jq -r 'join(",")')
+    LABELS=$(echo '${{ steps.issue.outputs.data }}' | jq -r '[.labels[].name]' | jq -r 'join(",")')
 
-        # Update PR Title
-        gh pr edit ${{ github.event.pull_request.number }} --title "$ISSUE_TITLE"
+    # Update PR Title
+    if [[ ! -z "$ISSUE_TITLE" ]]; then
+      gh pr edit ${{ github.event.pull_request.number }} --title "$ISSUE_TITLE"
+    fi
 
-        # Update PR Body
-        gh pr edit ${{ github.event.pull_request.number }} --body "Closes #${{ steps.extract.outputs.issue_number }}"
+    # Update PR Body
+    gh pr edit ${{ github.event.pull_request.number }} --body "Closes #${{ steps.extract.outputs.issue_number }}"
 
-        # Update PR Assignees
-        if [[ ! -z "$ASSIGNEES" ]]; then
-          gh pr edit ${{ github.event.pull_request.number }} --add-assignee "${ASSIGNEES}"
-        fi
+    # Update PR Assignees
+    if [[ ! -z "$ASSIGNEES" ]]; then
+      gh pr edit ${{ github.event.pull_request.number }} --add-assignee "${ASSIGNEES}"
+    fi
 
-        # Update PR Labels
-        if [[ ! -z "$LABELS" ]]; then
-          gh pr edit ${{ github.event.pull_request.number }} --add-label "${LABELS}"
-        fi
-      env:
-        GITHUB_TOKEN: ${{ secrets.TOKEN }}
-        jq: "sudo apt-get install jq -y"
+    # Update PR Labels
+    if [[ ! -z "$LABELS" ]]; then
+      gh pr edit ${{ github.event.pull_request.number }} --add-label "${LABELS}"
+    fi
+  env:
+    GITHUB_TOKEN: ${{ secrets.TOKEN }}
