Update auto_pr_title.yml

diff --git a/.github/workflows/auto_pr_title.yml b/.github/workflows/auto_pr_title.yml
--- a/.github/workflows/auto_pr_title.yml
+++ b/.github/workflows/auto_pr_title.yml
@@ -35,10 +35,41 @@ jobs:
 
     - name: Debug Issue Data
       run: echo "$ISSUE_DATA"
-      
-    - name: Update PR
+    - name: Update PR1
       run: |
-        ISSUE_TITLE=$(echo jq -r '.title' <<< "$ISSUE_DATA" )
+        ISSUE_TITLE=$(echo jq -r '.title' <<< \"$ISSUE_DATA\" )
+        if [ -z "$ISSUE_TITLE" ]; then
+          echo "Failed to fetch the issue title."
+          exit 1
+        fi
+    - name: Update PR2
+      run: |
+        ISSUE_TITLE=$(echo \"$ISSUE_DATA\" | jq -r .title)
+        if [ -z "$ISSUE_TITLE" ]; then
+          echo "Failed to fetch the issue title."
+          exit 1
+        fi
+      
+    - name: Update PR3
+      run: |
+        ISSUE_TITLE=$(echo \"$ISSUE_DATA\" | jq -r '.title')
+        if [ -z "$ISSUE_TITLE" ]; then
+          echo "Failed to fetch the issue title."
+          exit 1
+        fi
+
+
+    - name: Update PR4
+      run: |
+        ISSUE_TITLE=$(echo \"$ISSUE_DATA\" | jq -r \".title\")
+        if [ -z "$ISSUE_TITLE" ]; then
+          echo "Failed to fetch the issue title."
+          exit 1
+        fi
+        
+    - name: Update PR5
+      run: |
+        ISSUE_TITLE=$(echo jq -r .title <<< \"$ISSUE_DATA\" )
         if [ -z "$ISSUE_TITLE" ]; then
           echo "Failed to fetch the issue title."
           exit 1
